### ISSUE TITLE
Any plans for support spark 3.0 ?

### ISSUE THREAD

**Issue by luancaarvalho** [timgent/data-flare#144]

**Comment by timgent** [comment]
I'd love to add support for Spark 3.0 but struggle to find the time to add that currently. I'd be very happy to help someone else add a PR for this though. Would you be interested in helping?

**Comment by kingbrown9** [comment]
I'd also like that. @timgent what's the biggest thing that needs to get changed?

**Comment by timgent** [comment]
Scala 2.12 is already supported and published - https://search.maven.org/artifact/com.github.timgent/data-flare_2.12/2.4.5_0.1.14/jar

To migrate to Spark 3.0 I'd probably take this kind of approach:

* First just bump the relevant versions of dependencies
* See what breaks (compilation errors and tests should catch most things) and get an idea of how much work it is to fix
* Ultimately it'd be nice to keep the library backwards compatible with Spark 2, so would then have to look at how to support both. I think SBT has support for having multiple versions of the same files/classes and it chooses between them depending on the version it is building for. If you look in [build.sbt](https://github.com/timgent/data-flare/blob/master/build.sbt) and the [build script]https://github.com/timgent/data-flare/blob/master/mini-cross-build.py you can see some of the logic there for how the different versions of the library are built already

Happy to support if you want to give it a try!

**Comment by timgent** [comment]
Resolved in https://github.com/timgent/data-flare/pull/147

Data-flare version will remain the same, but existing artifacts will be published that are compatible with Spark 3. They should appear in Maven central in the next day or so
