### ISSUE TITLE
Check for comparing 2 tables are identical (will be less efficient than metrics based check)

### ISSUE THREAD

**Issue by timgent** [timgent/data-flare#97]

**Comment by rishabhishere** [comment]
Hi @timgent - Is this check only for ddl's (column/datatypes) or will it compare the contents of entire table ?

**Comment by timgent** [comment]
@rishabhishere the intention was for it to be of the entire table, including decent messages about differences (hence why this check type would be less efficient than the metric based checks, as this would involve a join).

Comparison of DDLs could be added separately if that would be helpful - if it's a feature you'd like to see please raise an issue.
